[tool.ruff]
line-length = 88
target-version = "py312"

[tool.lint]
elect = [
   "E",     # pycodestyle
   "F",     # pyflakes
   "I",     # isort
   "N",     # pep8-naming
   "W",     # pycodestyle warnings
   "UP",    # pyupgrade
   "B",     # flake8-bugbear
   "A",     # flake8-builtins
   "C4",    # flake8-comprehensions
   "RUF",   # ruff-specific
   "SIM",   # flake8-simplify
   "TCH"    # flake8-type-checking
]

[tool.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
